### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by bwhitty** [guyguyon/node-request-context#1]
Hello! I'm wondering if you could add a license to this project? I won't open a PR assuming to know what your desires are from a licensing perspective, but I think it will help others who are looking at this package.

Thank you!

**Comment by bruceharris** [comment]
Agreed, developers at most large enterprises won't be able to use this library without a license.

**Comment by guyguyon** [comment]
Hi, sorry for missing out this conversation. 
Sure, I can add a license. 
It is completely free open source. 
I guess MIT will be good for you guys @bwhitty @bruceharris ?

**Comment by guyguyon** [comment]
Done. Let me know if you have any concerns, otherwise I'll close this issue

**Comment by bwhitty** [comment]
Looks great, thanks a lot!
